name: Anonymous Video Upload PR

on:
  workflow_dispatch:
    inputs:
      video-file:
        description: 'Base64 encoded video file'
        required: true
      video-name:
        description: 'Name of the video file'
        required: true

jobs:
  process-upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Create new branch
      run: |
        BRANCH_NAME="add-video-${{ github.event.inputs['video-name'] }}-$(date +%s)"
        git checkout -b $BRANCH_NAME
        echo "branch_name=$BRANCH_NAME" >> $GITHUB_ENV

    - name: Decode and save video file
      run: |
        echo "${{ github.event.inputs['video-file'] }}" | base64 -d > previews/${{ github.event.inputs['video-name'] }}

    - name: Commit video file
      run: |
        git add previews/${{ github.event.inputs['video-name'] }}
        git commit -m "Add ${{ github.event.inputs['video-name'] }}"

    - name: Push new branch
      run: |
        git push origin ${{ env.branch_name }}

    - name: Create pull request
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        base: previews
        head: ${{ env.branch_name }}
        title: "Add ${{ github.event.inputs['video-name'] }}"
        body: "This PR adds the video ${{ github.event.inputs['video-name'] }}."
